server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  error:
    whitelabel:
      enabled: false 
spring:
  application:
    name: enjoy-diving-web
  output:
    ansi:
      enabled: always
  profiles:
    active: dev
  resources:
    chain:
      enabled: true
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML5
    template-resolver-order: 2
  messages:
    encoding: UTF-8
    cache-seconds: 5
    fallback-to-system-locale: false
    basename: i18n/messages 
  http:
    encoding:
      charset: UTF-8
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 3MB
  session:
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
  social:
    facebook:
      app-id: ENC(V6C597eeyQ7kBLMknP9JW658DyIyDFEg9/vya4RSwkE=)
      app-secret: ENC(e8d8vYGSi9+mCY61UG66tgeOFbjjJrxNbdjeb7NMM6GX/tIZwRkgUCFgsfXRKQ/z)
    google:
      app-id: ENC(Cq6BirD7Te7WRTl+uIeESO/8kYfAgIkEbpXcpdkb81jI0RaWtg6eAwH8NdnqE929RiYRd/XkokrBOCiXoyBv/PQRphMgkJEj41jC9WV+IfsEs9rLjGuwMA==)
      app-secret: ENC(BhvR8wFq/XPjeqFJzxh6nSaVcavsSYIA5yrRbhsHSlDa5XRBmWE0VQ==)
security:
  basic:
    enabled: false

---
# local
spring:
  profiles: local
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/diving
    username: sa
    password: test
    initialize: true
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: 127.0.0.1
    port: 6379

logging:
  level:
    root: DEBUG 
    org.apache: INFO
  config: classpath:config/logback-spring.xml
  file : local
  path : data/logs
  
props:
  apiBaseUrl: http://api.enjoydiving.io:8081
  google: 
    recaptcha:
      siteKey: 6LfLGYoUAAAAANmu-1CYbi2hS_cg98joNyU05u4p
      secretKey: 6LfLGYoUAAAAAK7lbr863C0hGj4BzyiVRG6dHUfR
---  

# dev
spring:
  profiles: dev
  datasource:
    url: ENC(JhbAOrO9c0MhlBJkcBhM15vkfabBJgxc4dxv+S93sxLPAcCMCjlXIfJFEBvXMNLr)
    username: ENC(jauxnix93NIxNidJQpxZGQ==)
    password: ENC(Jbk2+ry3C3T9suJEsBqWow==)
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: 127.0.0.1
    port: 6379
         
logging:
  level:
    root: DEBUG 
    org.apache: INFO
  config: classpath:config/logback-spring.xml
  file : dev
  path : data/logs

props:
  apiBaseUrl: http://api.enjoydiving.io:8081
  google: 
    recaptcha:
      siteKey: 6LfLGYoUAAAAANmu-1CYbi2hS_cg98joNyU05u4p
      secretKey: 6LfLGYoUAAAAAK7lbr863C0hGj4BzyiVRG6dHUfR

---  

# stg
spring:
  profiles: stg
  datasource:
    url: ENC(cfW7TvnQciD2KkBl35cty1vUKNw0FrSGi343dUOF2Nx9FrGx1GlRAU7XVC+GWR3+)
    username: ENC(jauxnix93NIxNidJQpxZGQ==)
    password: ENC(Jbk2+ry3C3T9suJEsBqWow==)
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: redis
    port: 6379
      
logging:
  level:
    root: INFO 
    org.apache: INFO
  config: classpath:config/logback-spring.xml
  file : stg
  path : data/logs
  
props:
  apiBaseUrl: http://enjoy-diving.biz:8081
  google: 
    recaptcha:
      siteKey: 6LfLGYoUAAAAANmu-1CYbi2hS_cg98joNyU05u4p
      secretKey: 6LfLGYoUAAAAAK7lbr863C0hGj4BzyiVRG6dHUfR
