version: '3'
services:
  mariadb:
    container_name: mariadb
    image: kbtapjm/mariadb:1.1
    restart: always
    volumes:
      - /opt/mysql:/var/lib/mysql
      - /opt/mysql/conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=diving
      - MYSQL_USER=diver
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul
    ports:
      - 3306:3306
    networks:
      - kbtapjm_default
    depends_on:
      - nginx
      - redis
  redis:
    container_name: redis
    image: kbtapjm/redis
    ports:
      - 6379:6379
    volumes:
      - /opt/redis/data:/data
    command: [ "redis-server", "--protected-mode", "no" ]
    restart: always
    networks:
      - kbtapjm_default
  enjoy-diving-service:
    container_name: enjoy-diving-service
    image: kbtapjm/enjoy-diving-service:0.0.1-SNAPSHOT
    networks:
      - kbtapjm_default
    ports:
      - 8081:8081
    volumes:
      - /opt/app/enjoy-diving-service/logs:/data/logs
    depends_on:
      - nginx
      - mariadb
      - redis
    restart: always
  enjoy-diving-web:
    container_name: enjoy-diving-web
    image: kbtapjm/enjoy-diving-web:0.0.1-SNAPSHOT
    networks:
      - kbtapjm_default
    ports:
      - 8080:8080
    volumes:
      - /opt/app/enjoy-diving-web/logs:/data/logs
    depends_on:
      - nginx
      - mariadb
      - redis
      - enjoy-diving-service
    restart: always
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /opt/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - kbtapjm_default
networks:
  kbtapjm_default:
    external: true